### ISSUE TITLE
Is this the only zbase32 in Python3?

### ISSUE THREAD

**Issue by internalG** [alanblevins/anybase32#2]
I find the http://pypi.python.org/pypi/zbase32/ is only available in python2. I searched a lot for python3 but no one available in pip. Is yours stable for production? Thanks.

**Comment by alanblevins** [comment]
I'm not sure if there are other libraries that support zbase32 in Python 3. My primary use case was supporting non-standard base32 alphabets, and at the time I implemented this, there did not appear to be any others.

I have used this successfully for a few small projects. My primary use case is relatively small base32 payloads returned from REST services. If you have very large base32 data to translate, the performance of this library may not be acceptable for your use case. The code is simple and the approach to translation is naive, which is fine for many use cases but not all. If you have any doubts, the code is only 100 lines and I encourage you to review it with your project in mind.

**Comment by internalG** [comment]
It runs well here. I think the zbase32 is very useful but not popular...
